const keywords = {
	"Agile": "After you perform a standard move, gain X dodge token(s). Note: climbing, embarking, disembarking, pivoting, and reversing are not standard moves. This effect does not trigger abilities that occur after dodge actions are performed.",
	"AI": "If you are on the battlefield, do not have a face up order token, and are not at range 3 of a commander unit. You must perform one of the specified actions as its first action that activation, if able. Free actions do not satisfy the requirements of AI.",
	"Aid": "When you would gain an aim, dodge, or surge token, another friendly unit of the affiliation or type listed at range 2 and in LOS may gain that token instead. If they do, you gain 1 suppression token.",
	"Allies of Convenience": "This unit may issue orders to friendly Mercenary units regardless of affiliation. During army building, you may have 1 extra Mercenary unit of any rank if you have at least one unit with this keyword. You cannot exceed normal rank limits this way.",
	"Area Weapon": "When using this weapon, perform a separate ranged attack against each friendly and enemy unit within LOS and this weapon's range, even if that unit is engaged. Area Weapon is indicated by a yellow range icon.",
	"Arm": "Place X of the specified charge tokens within range 1 and in LOS of your unit leader. Charge tokens cannot overlap objective, condition, or other charge tokens and must be placed on a flat surface.",
	"Armor": "While defending, cancel up to X hit results from the attack po. (Cancel all if no X listed)",
	"Arsenal": "When choosing weapons during the Form Attack Pool steps, each miniature in the unit that has Arsenal X keyword can contribute X weapons to the attack pool.  Each weapon may only be added to one attack pool.",
	"Associate": "During Army Building a unit with the Associate keyword does not count its rank towards the maximum rank requirements for that rank if a unit with the specified unit name is included in the same army.",
	"Ataru Mastery": "You can perform up to 2 attack actions during its activations. After you perform an attack, gain 1 dodge token. After defending, you gain 1 aim token.",
	"Attack Run":"At the start of its activation, a unit with the Attack Run keyword ma increase or decrease its maximum speed by 1 unit at the end of that activation.",
	"Authoritative": "Once per Command Phase, when you would be issued an order, you may instead issue an order to a friendly unit at range 1-2",
	"Bane Token":"Bane tokens (\"Here I Am\", \"Smoke and Mirrors\", \"Kablamo!\") are placed facedown, they cannot overlap objective or condition tokens. When an enemy mini moves, deploys, or is placed at Range 1 with LOS to the token, the token is revealed, its effect is resolved, then the token is removed. Minis cannot overlap Bane tokens.",
	"Kablamo!": "This token detonates using the weapon on Cad Bane's \"I Make the Rules Now\" Command Card.",
	"Smoke and Mirrors": "No effect.",
	"Here I Am": "If Cad Bane is not defeated, replace this token with him. If he was not already on the battlefield, he issues himself an order. At the start of each round, a player may reveal a friendly \"Here I Am\" token and resolve it.\n",
	"Barrage": "If you do not use ARSENAL during your activation, you may make 2 attack actions.",
	"Beam": "During the Declare Additional Defender step, you may choose up to X different targets using only this weapon. Additional targets must be against an enemy unit that is in LOS and within range 1 of the last defending unit declared. These additional attacks do not generate further attacks. Additional targets may be beyond this weapon's range.",
	"Blast": "Ignore cover.",
	"Block": "While defending, if you spend a dodge token, you gain surge to block.",
	"Bolster": "As an action, you may choose up to X friendly units at range 2. Each chosen unit gains 1 surge token.",
	"Bounty": "After setup, place a victory token on an enemy commander's or operative's card. The chosen unit gains a bounty token. After a friendly unit with the Bounty keywaord defeats an enemy unit that has one or more bounty tokesn with an attack or effect the friendly unit's controlling players scores 1 VP.",
	"Cache": "During Setup, place the listed tokens on this Upgrade Card. The unit owning the card may spend those tokens.",
	"Calculate Odds": "Choose a friendly trooper unit at range 2 and in LOS. It gains 1 aim, 1 dodge, and 1 suppression token",
	"Charge": "After you perform a move action, you may perform a free melee attack action.",
	"Climbing Vehicle": "You are treated as a trooper for the purposes of climbing.",
	"Complete The Mission": "During Setup, for each friendly unit with the Complete the Mission keyword, place a friendly priority mission token on the battlefield within contested territory. While at range 1 of one or more friendly priority mission tokens, that unit games surge to block.  While attacking an enemy unit at range 1 of a priority mission token, the attacking unit attack pool gains Critical 2 keyword.",
	"Compel": "After another friendly unit at range 2 of you rallies, if it is suppressed but not panicked, it may gain 1 suppression token to perform a free move action.",
	"Contingencies": "When building your command hand, set aside X additional Command Cards facedown. When revealing a Command Card, you may swap it for a Contingency Card with the same number of pips. (See Rulebook)",
	"Coordinate": "After you are issued an order, you may issue an order to a friendly unit with the name or type specified by X at range 1. Multiple Coordinates do not allow multiple orders to be issued, but do allow for each option listed to be used.",
	"Counterpart": "While building an army, this mini must be added to an X unit. (See Rulebook)",
	"Cover": "While defending against a ranged attack, improve your cover by X.",
	"Covert Ops": "During Setup, a unit with the Covert Ops keyword may change its rank of operative for the rest of the game. If it does, it gains the Infiltrate keyword that game. A unit cannot change its rank to operative if there are no other commander units in that palyer's army.",
	"Creature Trooper": "You can:  obscure other minis and provide light cover while doing so, pivot and reverse, displace troopers when moving through them. You do not:  improve your cover while you have 1 or more suppression tokens, get cover from barricades, embark or disembark, use CLAIM/SABOTAGE/REPAIR abilities, be displaced",
	"Critical": "While converting attack surges, you may convert up to X surge results to critical results.",
	"Cumbersome": "You cannot move prior to attacking with this weapon, unless the move is a pivot.",
	"Cunning": "When a Command Card belonging to you is revealed, if there would be a tie for priority, treat your Command Card as though it had 1 fewer pip.",
	"Cycle": "At the end of your activation, if you did not use this card, ready it.",
	"Danger Sense": "You may choose not to remove up to X of your suppression tokens (including 0). While defending against a ranged attack, roll 1 extra defense die for each suppression token you have, adding up to X extra dice.",
	"Dauntless": "After you rally, if you are suppressed but not panicked, you may gain 1 suppression token to perform a free move action. A Dauntless unit cannot be affected by COMPEL.",
	"Defend": "When you are issued an order, you gain X dodge tokens.",
	"Deflect": "While defending, if you spend a dodge token, any defense surge results are converted to block results; if it's a ranged attack, the attacker suffers 1 wound for each defense surge rolled.",
	"Demoralize": "After your Rally step, add up to X total suppression tokens to enemy units at range 1-2.",
	"Detachment": "During army building, you may only be included if a unit that has the name or type specified by X is also included in your army. Each unit with the DETACHMENT keyword requires a corresponding unit that matches the unit name or type specified. When you deploy, you must be within speed-1 and height 1 of the corresponding unit. You do not need to be within your deployment zone. See Rulebook.",
	"Detonate": "After a unit controlled by any player performs an action, you may detonate up to X of the specified friendly charge tokens. See Rulebook.",
	"Direct": "During the Command Phase, you may issue an order to a friendly unit with X at range 2.",
	"Disciplined": "When you are issued an order, you may remove up to X suppression tokens.",
	"Disengage": "You may perform moves while engaged with 1 unit.",
	"Distract": "Choose an enemy trooper at range 2 and in LOS. Until the end of the round, you lose INCONSPICUOUS and when that unit performs an attack, it must attack you, if able.",
	"Divine Influence":"While they are at range 1 of a friendly C-3PO, friendly Bright Tree trooper units gain Guardian 2: C-3PO.  While using Guardian, they may cancle Crit results as if they were hit results.",
	"Divulge": "You may reveal this card at the phase or step indicated. If you do, resolve its DIVULGE effect then return it to your hand.",
	"Djem So Mastery": "When a unit with Djem So Mastery keyword is defending against a melee attack, during the Compare Results step the attacking unit suffers a wound if the attack roll contacins one or more blank results.",
	"Droid Trooper": "Droid troopers do not lose actions and do not gain cover from suppression. Droids can still become panicked.",
	"Duelist": "While performing a melee attack, if you spend an aim token, gain Pierce 1. While defending against a melee attack, if you spend a dodge token, gain Immune:  Pierce. You still get the tokens' regular effects.",
	"Emplacement Trooper": "You can:  pivot, reverse. You cannot:  climb, use CLAIM/SABOTAGE/REPAIR, be displaced, be moved through by ground vehicles. This unit does not obscure LOS.",
	"Enrage": "While you have X or more wound tokens, treat your courage as \"-\", gain CHARGE, and lose any suppression tokens.",
	"Entourage": "During Army Building, a unit with the Entourage keyword does not count its rant towards the maximum rank requirements for that rank.  This can allow a player to bring more units of a specific rank than rank requirements allow. During the Issue Orders step a unit with Entourage keyword may issue an order to a friendly unit at range 2.  Additionally the unit specified by the Entourage keyword ignors the core rank requirement to provide backup to the unit with the Entourage keyword.",
	"Equip": "The listed upgrades must be equipped to this unit.",
	"Exemplar": "While at range 2 and in LOS of a unit that has the Exemplar keyword and that share the same faction or affiliations as that attacking or defending unit, may spend aim, dodge, and surge tokens of that friendly unit with Exemplar keyword.",
	"Expert Climber": "When this unit performs a climb, it may move a vertical distance up to height 2.",
	"Field Commander": "After a friendly neutral Command Card is played, you may be nominated as commander. Friendly units within command range of you may treat their courage as 3 when checking for panic. See Rulebook.",
	"Fire Support": "After a unit with the Fire Support keyword is issued an order it, gains a standby token.",
	"Fixed": "To add this weapon to the attack pool, the defender must have at least 1 mini partially inside the specified arc.",
	"Flawed": "Add your flaw card to an opponents hand.",
	"Flexible Response": "During Army Building, a unit with the Flexible Response keyword must equip X heavy weapon upgrades",
    "Full Pivot": "When you pivot, you can pivot up to 360 degrees.",
	"Generator": "During the End Phase, flip X inactive shield token(s).",
	"Graffiti Token": "During the Rally step of a friendly unit's activation:  if it has LOS to a friendly graffiti token at range 1-2, it may roll 1 additional die; if it has LOS to an enemy graffiti token at range 1-2, it must roll 1 fewer die, to a minimum of 1.",
	"Grounded": "You cannot climb.",
	"Guardian": "While a friendly trooper unit at range 1 and in LOS is defending against a ranged attack, it may cancel up to X hit results. For each result canceled this way, roll 1 of your defense dice. Convert any surges, then suffer 1 wound for each blank result. A unit cannot use Guardian X if it has a number of suppression tokens equal to or greater than its courage. Additionally a unit with Guardian X keyword cannot benefit from the backup and ignors the core rank requirement to provide backup.",
	"Guidance": "Choose another friendly trooper at range 2 to perform a free non-attack action.",
	"Gunslinger": "During the Declare Additional Defender step, you may declare an additional defender using a single weapon used in another attack. This can only be done once per attack sequence.",
	"Heavy Weapon Team": "You must equip a Heavy Weapon upgrade card. The mini added by that card is your unit leader.",
	"High Velocity": "While attacking, if each weapon in your attack pool has HIGH VELOCITY, the defender cannot spend dodge tokens.",
	"Hover: Ground/Air": "You can reverse, strafe, and standby. A unit with Hover: Ground keyword is treated as a ground vehicle by other units for all LOS purposes. For all other game effects, the unit is still treated as a respulsor vehicle. See Rulebook.",
	"Hunted": "During Setup, if one or more enemy units have the Bounty keyword, each unit with the Hunted keyword gains a bounty token.",
	"I'm, Part of the Squad Too": "A unit with the I', Part of the Squad Too keyword is contesting an objective token if its unit leader is at range 1 of that token instad of 1/2 range.",
	"Immobilize": "A unit suffering 1 or more wounds from an attack pool with this weapon gains X immobilize tokens. Reduce a unit's max speed by 1 per immobilize token. A unit with max speed 0 and one or more immobilize tokens cannot perform moves of any kind. Remove all of a unit's immobilize tokens at the end of its activation.",	
	"Immune": "X cannot be used against you.",
	"Impact": "While attacking a unit that has ARMOR, change up to X hit results to crit results.",
	"Impervious": "While defending, if the attack pool has PIERCE X, roll X additional defense dice. Do not roll these additional dice if you have IMMUNE: PIERCE.",
	"Incognito": "You cannot be attacked by enemy units beyond range 1 of it, cannot contest objectives, and cannot provide backup. IF a unt with Incognito keyword preforms an attack or defends against an attack, it loses all secial rules for the remainder of the game. Additionally at the bedinning of a unit with Incognito keyword's activation, it may choose to lose the special rules of the Incognito keyword for the remainder of the game.",
	"Inconspicuous": "If you have at least one suppression token, an enemy unit must target another unit, if able. During your Rally step, you may choose not to remove any number of your suppression tokens.",
	"Independent": "At the start of the Activation Phase, if you do not have an order token, gain X tokens.",
	"Indomitable": "During your Rally step, roll red defense dice instead of white.",
	"Infiltrate": "At the star of an undeployed unit with Infiltrate keyword's activation, it may deploy by placing the unit leader of that unit within friendly territory. Then the remaining miniatures in that unit are placed in cohesion with their leader unit and within friendly territory.  Miniatures cannot overlap impassable terrain when they are placed using Infiltrate.",
	"Inspire": "At the end of a unit with the Inspire X keyword's activation remove up to X total suppression tokens from other friendly units at range 2.",
	"Interrogate": "During the Command Phase if a player reveals a Command Card that belongs to a unit at/within range 1 of one or more enemy units with the Interrogate keyword and there would be a tie for priority, treat that command card as having one more pip.",
	"Ion": "A vehicle or droid wounded by an attack that included this weapon gains X ion tokens. At the start of the Modify Attack Dice step, before any other effects, any unit defending against this weapon must flip an active shield token, if able, for each hit or critical result, up to X.",
	"Ion Token": "At the start of a unit's activation, if it has 1 or more ion tokens, roll one white defense die for every ion token that unit has. If any blank results are rolled, that unit performs one fewer action during its activation.",
	"Jar'Kai Mastery": "While preforming a melee attack, after converting attack surges, a unit with the Jar'Kai Mastery keyword may spend any number of dodge tokens. For each dodge token spent in this way change a blank result to a hit, a hit result to a crit, or spend 2 dodges tokens to change a blank result to a crit.",
	"Jedi Hunter": "While attacking a unit that has a Force upgrade icon, you gain surge to crit.",
	"Jump": "Perform a move during which you ignore terrain that is height X or lower, measuring height from starting position. This is treated as a move action.",
	"Juyo Mastery": "While you are wounded, you can perform 1 additional action during your activation. Limit 2 move actions.",
	"Latent Power": "At the end of your activation, you may gain 1 suppression token to roll 1 red defense die. On a focus result, give an enemy unit at range 1 and give them 2 suppression tokens and 2 immobilize tokens. On a blank result, remove 1 wound or 1 poison token from a friendly non-droid trooper at range 1.",
	"Leader": "This mini is your unit leader. Limit 1 LEADER per unit.",
	"Lethal": "You may spend up to X aim tokens during the Modify Attack Dice step. If you do, the attack pool gains Pierce 1 for each aim token spent.",
	"Loadout": "During Setup, a unit with Loadout keyword may swap any number of its equipped Upgrade Cards with the matching set-aside Upgrade Cards one for one.  When swapping Upgrade Cards, a unit cannot have two or more upgrades with the same name equipped at the same time.  Each unit can swap Upgrade Cards only with their own set-aside cards.  A Counterpart Card that is added to a unit with Loadout keyword also benefits from the Loadout ability. ",
	"Long Shot": "While attacking, spend up to X aim tokens to increase this weapon's maximum range by 1 for each aim token spent.",
	"Low Profile": "While defending against a ranged attack if a unit with the Low Profile keyword would roll one or more defense dice during the Roll Cover Pool step, it rolls one fewer defnese die and instead adds one additional block result to the cover pool after rolling.",
	"Makashi Mastery": "While performing a melee attack, you may reduce the PIERCE value of your melee weapon by 1. If you do, the defender cannot use IMMUNE: PIERCE or IMPERVIOUS.",
	"Marksman": "After converting attack surges, you can spend any nunber of aim tokens. For each token spent, convert a blank to a hit, a hit to a crit, or spend 2 tokens to convert a blank to a crit.",
	"Master of the Force": "At the end of its activation, this unit may ready up to X of its exhausted Force upgrade cards.",
	"Master Storyteller": "When a unit preforms the Master Storyteller card action, it chooses up to X friendly Bright Tree units at range 2, where X is the current round number.  Each chosen unit gains 2 surge tokens.",
	"Mercenary: Faction": "A unit with the Mercenary keyword is a Mercnary unit. The faction(s) specified by the Mercenary keyword can include that unit in an army as a Mercenary unit.",
	"Nimble": "After defending, if you spent 1 or more dodge tokens, gain 1 dodge token.",
	"Noncombatant": "This mini cannot use any weapons and wounds must be assigned to other non-unit leader minis first.",
	"Observe": "Choose an enemy unit at range 1-3 and in LOS. It gains X observation tokens.",
	"Outmaneuver": "You can spend dodge tokens to cancel critical hit results.",
	"Override": "When a friendly unit begins its activation at range 5 of a unit that has the Override keyword, it may gain 1 suppression token. If it does, the activating unit ignores AI during its activation.",
	"Overrun":"A unit may make X overrun attacks during its activation. A unit can perform an overrun attack after it makes a standard move during which one of its minis bases overlapped an enemy mini's base. After completing the move and resolving any displacement of the enemy unit, perform an attack against the unit you moved through, ignoring range. You can form only one attack pool, using only OVERRUN weapons and only adding the overrun weapon once, even if multiple minis are in the attack. If a unit has OVERRUN greater than 1, it must perform a separate move for each overrun attack.",
	"Permanent": "This card is not discarded at the End Phase, its effect persists as long as it's in play.",
	"Pierce": "While attacking, cancel up to X block results.",
	"Plodding": "During your activation, you can perform only 1 move action.",
	"Poison": "A non-droid trooper unit suffering wounds from this weapon gains X poison tokens.",
	"Poison Token": "At the end of a unit's activation, it suffers 1 wound for each poison token it has, then discards each poison token it has. Vehicles and droid trooper units cannot gain poison tokens.",
	"Precise": "When you spend an aim token, reroll up to X additional dice.",
	"Prepared Position": "A uint with the Prepared Position keyword may deploy by placing the unit leader of that unit within friendly territory.  Then the remaining minatures in that unit are placed in cohesion with their unit leader and within friendly territory. That uint then gains 1 dodge token. Minis cannoot overlap impassable terrain when they are placed using Prepared Position.",
	"Programmed": "During Army Building, you must equip at least 1 Protocol upgrade",
	"Pulling the Strings": "Choose a friendly trooper unit at range 1-2. That unit may perform a free attack action or a free move action.",
	"Quick Thinking": "Gain 1 aim token and 1 dodge token.",
	"Ram": "During the Modify Attack Dice step, you may change X attack die results to crit results if you performed at least 1 full standard move at max speed during the same activation as this attack.",
	"Ready": "After you perform a standby action, gain X aim tokens.",
	"Recharge": "When you recover, flip up to X inactive shield tokens to their active side.",
	"Reconfigure": "When you recover, you may flip this card. Reconfigure does not exhaust this card.",
	"Regenerate": "At the end of your activation, roll 1 white defense die for each wound token you have, up to X. For each defense surge or block result, remove 1 wound token.",
	"Reinforcements": "At the start of the End Phase of the first round of a game, a unit with the Reinforcements keyword may preform a free speed-1 move.",
	"Relentless": "After you perform a move action, you may perform 1 free attack action.",
	"Repair": "Choose a friendly droid trooper or vehicle unit at range 1 and in LOS. Place 1 wound token on this card to remove up to X wound, ion, or vehicle damage tokens from the chosen unit, or to RESTORE X minis to that unit. You cannot do this action if this card has Y wound tokens. If you have multiple Repairs, treat each as a separate ability.",
	"Reposition": "Either before or after you perform a standard move, you may perform a free pivot action.",
	"Restore": "Choose a unit, then select a mini from this unit defeated in the current round. Place that mini in cohesion with its unit leader, then give it wound tokens equal to one less than its wound threshold",
	"Retinue": "At the start of the Activation Phase, if you are at range 2 of X, gain 1 aim or dodge token. Additionally, a unit with Retinue keyword ignors the core rank requirments to provide backup to the specified unit.",
	"Ruthless": "When another friendly Corps trooper unit at range 2 and in LOS that has a faceup order token activates, it may suffer 1 wound to perform 1 free action.",
	"Sidearm Melee/Ranged": "If an upgrade has Sidearm:Melee keyword, the minatirue added by that upgraad or with that upgrade cannot add any melee weapons to attack pools other than any melee weapons on the Upgrade Card with Sidearm: Melee.  (Same effect for ranged)",
	"Scale": "When you perform a climb, you may move a vertical distance of up to height 2. Do not reduce maximum speed when moving through difficult terrain.",
	"Scatter": "After performing an attack against a trooper unit with small bases, you may move any non-leader minis in the defending unit, following the all the rules of cohesion, as if the unit leader had performed a standard move.",
	"Scout": "At the start of its Perform Actions step, it may deploy by performing a free speed X move action, ignoring difficult terrain. A unit can perform this move regardless of its maximum speed. The Scout X keyword is cumulative, but cannot exceed 3. If a unit would ever have Scout X eceeding Scout 3, it has Scout 3 instead.",
	"Scouting Party": "During Setup, a unit with Scouting Party keyword may choose up to X friendly trooper units that share the same faction or affiliation with that unit and do not have the scout keyword. Each chosen unit gains the Scout X keyword this game, where X is the Scout X value of the uint with the Scouting Pary keyword.",
	"Secret Mission": "Once per game if a unit with the Secret Mission keyword is within enemy territory, it gains a secret mission token. When scoring VP, if a player with 1 or more secret mission tokens is within enemy territory that unit scores 1 VP. Then, remove those secret mission tokens from the game.",
	"Self-Destruct": "You may perform this attack as a free action if you have at least X wound tokens. Perform this attack against all unit within range 1 and LOS, even if they are engaged. This attack my not be performed by a unit embarked on a TRANSPORT. After performing all attacks, the unit making this attack is defeated and removed from play.",
	"Self-Preservation": "When checking for panic, this unit cannot use the courage value of of units not of the same affiliation.",
	"Sentinel": "Your standby range is 1-3.",
	"Sharpshooter": "While performing a ranged attack, reduce the defender's cover by X.",
	"Shield Token": "While defending against a ranged attack, during the Apply Dodge and Cover step, a unit may flip any number of active shield tokens. For each shield token flipped this way, the defender cancels 1 hit or crit result.",
	"Shielded": "You have X shield tokens",
	"Sidearm": "While performing an attack, this mini can only use the weapon on this upgrade card if the attack type matches X.",
	"Skirmish": "Intended for use in Skirmish matches.",
	"Small": "While defending against a non-area ranged attack, ignore this mini.",
	"Smoke": "Place X smoke token(s) within range 1 and in LOS of your unit leader.",
	"Soresu Mastery": "While defending agains a ranged attack, it may reroll all of its defense dice during the Reroll Defense Dice step. Additionally, when using the Guardian X keyword, it may spend one dodge token before converitng any surges. If it does, it rerolls all of its defense dice before converting surges. Each die cannot be rerolled more than once.",
	"Special Issue": "This unit may only be included in X battleforce",
    "Speeder": "While moving, ignore terrain that is height X or lower. When at the start or end of your activation, you must perform a free compulsory move. Additionally, a notched based unit perfroms a move, it skips step 1 of notched base movement, rotating the unit leader's base. If a unit performs more than one non-compulsory move actions, it may not claim asset tokens that activation.  Additionally, a unit that has claimed an asset token can perform only one non-compulsory move actions during its activation.",
	"Spotter": "Choose X friendly units at range 2. Each unit gains an aim token.",
	"Spray": "Add this weapon's dice to the attack pool one time for each mini in the defending unit to which LOS is not blocked.",
	"Spur": "While performing a move, you may gain 1 suppression token to increase your maximum speed by 1.",
	"Stationary": "You cannot perform moves, except pivots.",
	"Steady": "After you perform a move action, you may perform a free ranged attack action.",
	"Strategize": "Gain 1 suppression token and choose X friendly units at range 2. The chosen units each gain 1 aim and 1 dodge token.",
	"Suppressive": "After you perform an attack, the defender that this weapon was used against gains 1 suppression token.",
	"Surge Token": "Spending one or more surge tokens will convert the same number of surges to blocks while defending or using using GUARDIAN, and to hits while attacking.",
	"Tactical": "After you perform a standard move, gain X aim tokens.",
	"Take Cover": "Choose X friendly trooper units at range 2. Each unit gains a dodge token.",
	"Target": "After you are issued an order, gain X aim tokens.",
	"Teamwork": "While you are at range 2 of X, when you or X gains an aim or dodge token, the other unit gains a token of the same type.",
	"Tempted": "If a friendly unit is defeated by an enemy attack and that attacking unit is at range 3 of a unit with Tempted, it may preform a speed 2 move ignoring difficutl terrain after the attack actions is resloved. A unit may use the Tempted keyword only once each round.",
	"Tow Cable": "After a vehicle is wounded by an attack that includes this weapon, the attacker performs a pivot with that vehicle.",
	"Transport":"During Setup you may choose a friendly core trooper or special forces trooper unit to transport. During the Issue Order step of the Command Phase of round1, a unit with Transport may issue an order to the chosen unit. If the chosen unit is undeployed when the Transport unit deploys, after the effect is resloved the chosen unit deploys by preforming a speed 1 move. Measure the start with both prongs of the movement tool touching the base of the Transport.",
	"Treat": "Choose a friendly non-droid trooper unit at range 1 and in LOS and place a wound token on this card. Remove up to X wound or poison tokens from that unit or restore up to X miniatures to that unit. You cannot use this ability if this card has Y or more wound tokens. If you have multiple TREAT keywords, treat them as separate abilities.",
	"Uncanny Luck": "While defending, you may reroll up to X defense dice. All dice must be rerolled at once, no die can be rerolled twice.",
	"Unconcerned": "You cannot benefit from cover, minis in this unit cannot be repaired or restored.",
	"Unhindered": "You ignore the effects of difficult terrain.",
	"Unstoppable": "This unit is eligible to activate while it has one or fewer facedown order tokens. This unit may never have more than one faceup order token. While this unit is not defeated, when creating its order pool, its controlling player adds an additional order token for this unit to the order pool",
	"Vehicle": "You can:  pivot, block LOS. Ground vehicles can:  reverse, move through repulsor vehicles, perform the standby action, obscure other minis and provide cover. Repulsor vehicles:  can move through troopers and vehicles.",
	"Versatile": "You can perform ranged attacks using this weapon while engaged.",
	"Weak Point": "While defending, if the attacker's unit leader is inside the listed arc(s), the attack pool gains IMPACT X.",
	"Weighed Down": "While a unit has a claimed objective token, it cannot use the Jump keyword",
	"We're Not Regs": "Unit may not spend green tokens on other Clone Troopers and other Clone Trooper units may not spend this unit's green tokens.  Additionally, this unit cannot benefit from backup.",
	"Wheel Mode": "At the start of your activation, as a free action, you may increase your maximum speed to 3. If you do, until the end of the round, you gain COVER 2 and cannot attack or flip active shield tokens.",
	"Wound": "The first time you enter play, you suffer X wounds.",
}

export default keywords;